import { agentLoader } from './agentLoader.js';
import { stateMachine } from './stateMachine.js';
import { fallbackManager } from './fallback.js';

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function runMilestone1Test() {
  console.log('\n===============================================================');
  console.log('       THE OFFICE - MILESTONE 1 VERIFICATION & TEST SUITE       ');
  console.log('===============================================================\n');

  // STEP 1: Inspect Loaded Agents
  console.log('--- [Step 1: Loaded Agent Registry] ---');
  const allAgents = agentLoader.getAllAgents();
  console.log(`Total configured agents: ${allAgents.length}`);
  allAgents.forEach((agent, idx) => {
    console.log(
      `  ${idx + 1}. [${agent.id.padEnd(14)}] ${agent.name.padEnd(26)} | API: ${agent.api.padEnd(14)} | Model: ${agent.model}`
    );
  });

  // STEP 2: Normal Task Execution Lifecycle
  console.log('\n--- [Step 2: Normal Lifecycle Transitions] ---');
  console.log('Simulating PM & Idea Generator starting tasks...');

  // PM starts working on brief
  stateMachine.transition('pm', 'working', {
    currentTask: 'Decomposing user brief: Photographer Portfolio',
  });
  await sleep(400);

  // Idea generator starts
  stateMachine.transition('idea', 'working', {
    currentTask: 'Generating layout concepts and copy',
  });
  await sleep(400);

  // PM finishes decomposition
  stateMachine.transition('pm', 'done', {
    currentTask: 'Task decomposition complete (9 subtasks created)',
    tokensUsed: 420,
  });
  await sleep(300);

  // Designer starts
  stateMachine.transition('designer', 'working', {
    currentTask: 'Creating dark-mode glassmorphic color palette & grid',
  });
  await sleep(400);

  // Designer requests review / debugging
  stateMachine.transition('designer', 'debugging', {
    currentTask: 'Refining typography contrast ratios',
  });
  await sleep(300);

  stateMachine.transition('designer', 'done', {
    currentTask: 'Design tokens & spec ready',
    tokensUsed: 650,
  });

  // STEP 3: Rate Limit & Fallback Cooldown Simulation
  console.log('\n--- [Step 3: Quota Error & Fallback ("Coffee Break") Mechanism] ---');
  console.log('Simulating HTML Developer hitting API quota limit (HTTP 429)...');

  stateMachine.transition('html_dev', 'working', {
    currentTask: 'Building semantic HTML for portfolio gallery',
  });
  await sleep(400);

  const mockQuotaError = new Error('HTTP 429: Too Many Requests - Quota exceeded for model qwen-2.5-coder-32b');
  mockQuotaError.status = 429;

  // Trigger fallback handler with a short 2-second cooldown for test demonstration
  const fallbackResult = fallbackManager.handleAgentFailure(
    'html_dev',
    { id: 'task_003', title: 'Building semantic HTML for portfolio gallery' },
    mockQuotaError,
    2 // 2 second cooldown for fast test
  );

  console.log(`Fallback Action Result:`, fallbackResult);
  await sleep(500);

  // Check state of assigned fallback (css_dev)
  const cssState = stateMachine.getState('css_dev');
  console.log(`Current state of fallback agent (css_dev): ${cssState.status} | Task: "${cssState.currentTask}"`);

  // css_dev finishes the task
  stateMachine.transition('css_dev', 'done', {
    currentTask: 'HTML markup generated by fallback agent',
    tokensUsed: 780,
  });

  // Wait for html_dev's cooldown (2 seconds) to finish
  console.log('Waiting for html_dev coffee break cooldown to expire...');
  await sleep(2200);

  const htmlDevState = stateMachine.getState('html_dev');
  console.log(`html_dev state after cooldown: \x1b[1m${htmlDevState.status}\x1b[0m (Back to idle, ready for next task)`);

  // STEP 4: Summary Table
  console.log('\n--- [Step 4: Live Agent States Summary] ---');
  const summary = stateMachine.getAllStates().map((s) => ({
    Agent: s.agentId,
    Status: s.status,
    CompletedTasks: s.stats.tasksCompleted,
    Breaks: s.stats.breaksTaken,
    Tokens: s.stats.tokensUsed,
    CurrentTask: s.currentTask ? s.currentTask.slice(0, 35) + '...' : 'None',
  }));
  console.table(summary);

  console.log('\n===============================================================');
  console.log('     MILESTONE 1 VERIFICATION COMPLETED SUCCESSFULLY!          ');
  console.log('===============================================================\n');
}

runMilestone1Test().catch((err) => {
  console.error('Test execution failed:', err);
  process.exit(1);
});
