// LUMEN Interactive Behavior - Generated by JS Developer
document.addEventListener('DOMContentLoaded', () => {
  // 1. Gallery category filtering
  const filterButtons = document.querySelectorAll('.filter-btn');
  const galleryItems = document.querySelectorAll('.gallery-item');

  filterButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      filterButtons.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      const filter = btn.getAttribute('data-filter');
      galleryItems.forEach(item => {
        if (filter === 'all' || item.getAttribute('data-category') === filter) {
          item.style.display = 'block';
        } else {
          item.style.display = 'none';
        }
      });
    });
  });

  // 2. Inquiry form submission
  const inquiryForm = document.getElementById('inquiryForm');
  const feedback = document.getElementById('formFeedback');

  if (inquiryForm) {
    inquiryForm.addEventListener('submit', async (e) => {
      e.preventDefault();
      const name = document.getElementById('name').value;
      const email = document.getElementById('email').value;

      feedback.style.color = '#38bdf8';
      feedback.textContent = 'Processing inquiry...';

      setTimeout(() => {
        feedback.style.color = '#4ade80';
        feedback.textContent = `Thank you ${name}! We received your inquiry and sent confirmation to ${email}.`;
        inquiryForm.reset();
      }, 700);
    });
  }
});
